"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"preserve_hierarchy": true

export_languages:
  - ar
  - de
  - el
  - es-ES
  - fr
  - hi
  - id
  - it
  - ja
  - ko
  - ms
  - pl
  - pt-BR
  - ru
  - sv-SE
  - th
  - tr
  - uk
  - vi
  - zh-CN
  - zh-HK

files:
  - source: /talos/src/locale/data/ui/en-US.json
    translation: /talos/src/locale/data/ui/%locale%.json
    excluded_target_languages:
      - la-LA
    languages_mapping:
      locale:
        ar: ar-SA
        de: de-DE
        el: el-GR
        fr: fr-FR
        hi: hi-IN
        id: id-ID
        it: it-IT
        ja: ja-JP
        ko: ko-KR
        ms: ms-MY
        pl: pl-PL
        ru: ru-RU
        th: th-TH
        tr: tr-TR
        uk: uk-UA
        vi: vi-VN
