
/**
 * @description (generated by gpt) Downloads a JavaScript object as a JSON file.
 *
 * @param {Object} exportObj - The object to be exported as JSON.
 * @param {string} exportName - The name of the exported JSON file (without extension).
 */
function downloadObjectAsJson(exportObj, exportName) {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(exportObj));
    const downloadAnchorNode = document.createElement('a');
    downloadAnchorNode.setAttribute("href", dataStr);
    downloadAnchorNode.setAttribute("download", exportName + ".json");
    document.body.appendChild(downloadAnchorNode); // required for firefox
    downloadAnchorNode.click();
    downloadAnchorNode.remove();
}

export { downloadObjectAsJson };